@echo off
setlocal
REM Madmona CapCut - ALL-IN-ONE v2 (no key to paste). Double-click.
set TARGET=C:\madmona-capcutapi
if not exist "%TARGET%\requirements.txt" ( echo ERROR: run the installer first & pause & exit /b 1 )
cd /d "%TARGET%"
echo [1/3] Writing the worker...
if exist worker_b64.txt del worker_b64.txt
echo IyAtKi0gY29kaW5nOiB1dGYtOCAtKi0KIiIiTWFkbW9uYSBDYXBDdXQgUmVlbCBXb3JrZXIgLSBTVEVQIDEgKHNlcnZlci1wcm94>>worker_b64.txt
echo eSBhdXRoLCBubyBrZXkgdG8gcGFzdGUpIiIiCmltcG9ydCBvcywganNvbiwgdGltZSwgdHJhY2ViYWNrLCByZXF1ZXN0cwpmcm9t>>worker_b64.txt
echo IGNyZWF0ZV9kcmFmdCBpbXBvcnQgY3JlYXRlX2RyYWZ0CmZyb20gYWRkX3RleHRfaW1wbCBpbXBvcnQgYWRkX3RleHRfaW1wbApm>>worker_b64.txt
echo cm9tIHNhdmVfZHJhZnRfaW1wbCBpbXBvcnQgc2F2ZV9kcmFmdF9pbXBsCgpBUEkgPSAiaHR0cHM6Ly9tamhmbHhweHVud3ljYmlx>>worker_b64.txt
echo dW9pZy5zdXBhYmFzZS5jby9mdW5jdGlvbnMvdjEvY2FwY3V0LXdvcmtlci1hcGkiCktFWSA9ICJja18wMWRiYzRmYjk1ZGY0MDg1>>worker_b64.txt
echo YWVmOWEwYjUiCkhEUiA9IHsieC1jYXBjdXQta2V5IjogS0VZLCAiQ29udGVudC1UeXBlIjogImFwcGxpY2F0aW9uL2pzb24ifQoK>>worker_b64.txt
echo ZGVmIGZpbmRfY2FwY3V0X2RyYWZ0X2RpcigpOgogICAgbGEgPSBvcy5lbnZpcm9uLmdldCgiTE9DQUxBUFBEQVRBIiwgIiIpCiAg>>worker_b64.txt
echo ICBmb3IgYyBpbiBbb3MucGF0aC5qb2luKGxhLCAiQ2FwQ3V0IiwgIlVzZXIgRGF0YSIsICJQcm9qZWN0cyIsICJjb20ubHZlZGl0>>worker_b64.txt
echo b3IuZHJhZnQiKSwKICAgICAgICAgICAgICBvcy5wYXRoLmpvaW4obGEsICJKaWFueWluZ1BybyIsICJVc2VyIERhdGEiLCAiUHJv>>worker_b64.txt
echo amVjdHMiLCAiY29tLmx2ZWRpdG9yLmRyYWZ0IildOgogICAgICAgIGlmIG9zLnBhdGguaXNkaXIoYyk6CiAgICAgICAgICAgIHJl>>worker_b64.txt
echo dHVybiBjCiAgICByZXR1cm4gTm9uZQoKZGVmIGFwaShhY3Rpb24sICoqa3cpOgogICAgYm9keSA9IHsiYWN0aW9uIjogYWN0aW9u>>worker_b64.txt
echo fTsgYm9keS51cGRhdGUoa3cpCiAgICByID0gcmVxdWVzdHMucG9zdChBUEksIGhlYWRlcnM9SERSLCBkYXRhPWpzb24uZHVtcHMo>>worker_b64.txt
echo Ym9keSksIHRpbWVvdXQ9NDApCiAgICByLnJhaXNlX2Zvcl9zdGF0dXMoKTsgcmV0dXJuIHIuanNvbigpCgpkZWYgYnVpbGRfZHJh>>worker_b64.txt
echo ZnQoam9iLCBkcmFmdF9kaXIpOgogICAgc2NlbmVzID0gam9iLmdldCgic2NlbmVzIikgb3IgW10KICAgIGlmIGlzaW5zdGFuY2Uo>>worker_b64.txt
echo c2NlbmVzLCBzdHIpOiBzY2VuZXMgPSBqc29uLmxvYWRzKHNjZW5lcykKICAgIHRvdGFsID0gam9iLmdldCgidG90YWxfZHVyYXRp>>worker_b64.txt
echo b25fc2VjIikgb3IgbWF4KDE1LCBsZW4oc2NlbmVzKSAqIDUpCiAgICBwZXIgPSBtYXgoMi4wLCByb3VuZCh0b3RhbCAvIG1heCgx>>worker_b64.txt
echo LCBsZW4oc2NlbmVzKSksIDIpKQogICAgc2NyaXB0LCBkcmFmdF9pZCA9IGNyZWF0ZV9kcmFmdCgxMDgwLCAxOTIwKQogICAgdCA9>>worker_b64.txt
echo IDAuMAogICAgZm9yIGksIHNjIGluIGVudW1lcmF0ZShzY2VuZXMpOgogICAgICAgIHR4dCA9IChzYy5nZXQoInRleHQiKSBvciAi>>worker_b64.txt
echo Iikuc3RyaXAoKQogICAgICAgIGlmIG5vdCB0eHQ6CiAgICAgICAgICAgIHQgKz0gcGVyOyBjb250aW51ZQogICAgICAgIGVkZ2Ug>>worker_b64.txt
echo PSAoaSA9PSAwIG9yIGkgPT0gbGVuKHNjZW5lcykgLSAxKQogICAgICAgIGFkZF90ZXh0X2ltcGwodGV4dD10eHQsIHN0YXJ0PXQs>>worker_b64.txt
echo IGVuZD10ICsgcGVyLCBkcmFmdF9pZD1kcmFmdF9pZCwKICAgICAgICAgICAgICAgICAgICAgIGZvbnRfY29sb3I9IiNGRkQ3MDAi>>worker_b64.txt
echo IGlmIGVkZ2UgZWxzZSAiI0ZGRkZGRiIsCiAgICAgICAgICAgICAgICAgICAgICBmb250X3NpemU9MTEuMCBpZiBlZGdlIGVsc2Ug>>worker_b64.txt
echo OS4wLCB0cmFuc2Zvcm1feT0wLjAsIHRyYWNrX25hbWU9InRleHRfbWFpbiIpCiAgICAgICAgdCArPSBwZXIKICAgIHNhdmVfZHJh>>worker_b64.txt
echo ZnRfaW1wbChkcmFmdF9pZCwgZHJhZnRfZGlyKQogICAgcmV0dXJuIGRyYWZ0X2lkCgpkZWYgbWFpbigpOgogICAgZHJhZnRfZGly>>worker_b64.txt
echo ID0gZmluZF9jYXBjdXRfZHJhZnRfZGlyKCkKICAgIGlmIG5vdCBkcmFmdF9kaXI6CiAgICAgICAgcHJpbnQoIkVSUk9SOiBDYXBD>>worker_b64.txt
echo dXQgZHJhZnRzIGZvbGRlciBub3QgZm91bmQuIElzIENhcEN1dCBEZXNrdG9wIGluc3RhbGxlZD8iKTsgcmV0dXJuCiAgICBwcmlu>>worker_b64.txt
echo dCgiQ2FwQ3V0IGRyYWZ0cyBmb2xkZXI6IiwgZHJhZnRfZGlyKQogICAgcHJpbnQoIkNvbm5lY3RlZC4gUG9sbGluZyBmb3IgQ2Fw>>worker_b64.txt
echo Q3V0IHJlZWxzLi4uICAoQ3RybCtDIHRvIHN0b3ApIikKICAgIHdoaWxlIFRydWU6CiAgICAgICAgdHJ5OgogICAgICAgICAgICBq>>worker_b64.txt
echo b2JzID0gYXBpKCJqb2JzIikuZ2V0KCJqb2JzIiwgW10pCiAgICAgICAgICAgIGlmIGpvYnM6CiAgICAgICAgICAgICAgICBwcmlu>>worker_b64.txt
echo dCgiXG4lZCByZWVsKHMpIHRvIGJ1aWxkLiIgJSBsZW4oam9icykpCiAgICAgICAgICAgICAgICBmb3IgaiBpbiBqb2JzOgogICAg>>worker_b64.txt
echo ICAgICAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgICAgICAgICAgZGlkID0gYnVpbGRfZHJhZnQoaiwgZHJhZnRfZGly>>worker_b64.txt
echo KQogICAgICAgICAgICAgICAgICAgICAgICBhcGkoIm1hcmtfYnVpbHQiLCBpZD1qWyJpZCJdLCBkcmFmdF9pZD1kaWQpCiAgICAg>>worker_b64.txt
echo ICAgICAgICAgICAgICAgICAgIHByaW50KCIgIFtPS10gJXMgIC0+ICAlcyIgJSAoai5nZXQoInRpdGxlIiksIGRpZCkpCiAgICAg>>worker_b64.txt
echo ICAgICAgICAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgICAgICAgICAgICAgICAgICBwcmludCgiICBbRkFJ>>worker_b64.txt
echo TF0gJXM6ICVzIiAlIChqLmdldCgidGl0bGUiKSwgZSkpOyB0cmFjZWJhY2sucHJpbnRfZXhjKCkKICAgICAgICAgICAgICAgIHBy>>worker_b64.txt
echo aW50KCJEb25lLiBPcGVuIENhcEN1dCBEZXNrdG9wIHRvIHNlZSB0aGUgZHJhZnRzLiIpCiAgICAgICAgICAgIGVsc2U6CiAgICAg>>worker_b64.txt
echo ICAgICAgICAgICBwcmludCgiLiIsIGVuZD0iIiwgZmx1c2g9VHJ1ZSkKICAgICAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAg>>worker_b64.txt
echo ICAgICAgICAgIHByaW50KCJwb2xsIGVycm9yOiIsIGUpCiAgICAgICAgdGltZS5zbGVlcCgyMCkKCmlmIF9fbmFtZV9fID09ICJf>>worker_b64.txt
echo X21haW5fXyI6CiAgICBtYWluKCkK>>worker_b64.txt
powershell -NoProfile -Command "[IO.File]::WriteAllBytes('%TARGET%\capcut_reel_worker.py',[Convert]::FromBase64String((Get-Content 'worker_b64.txt' -Raw)))" 
del worker_b64.txt
if not exist "%TARGET%\capcut_reel_worker.py" ( echo WRITE FAILED & pause & exit /b 1 )
echo [2/3] Installing dependencies (one time)...
python -m pip install -r requirements.txt
python -m pip install requests
echo [3/3] Starting the worker...
echo.
python capcut_reel_worker.py
pause