// 🔗 يقرا بايو تيك توك + وجود لينك من كروم السوشيال (CDP 9223)
const { chromium } = require('playwright')
;(async () => {
  const b = await chromium.connectOverCDP('http://127.0.0.1:9223', { timeout: 20000 })
  const page = await b.contexts()[0].newPage()
  await page.goto('https://www.tiktok.com/@madmonacairo', { waitUntil: 'domcontentloaded', timeout: 60000 }).catch(()=>{})
  await page.waitForTimeout(6000)
  const r = await page.evaluate(() => ({ url: location.href, title: document.title.slice(0,60), bio: (document.querySelector('[data-e2e="user-bio"]')||{}).innerText, link: (document.querySelector('[data-e2e="user-link"]')||{}).innerText, editBtn: !!document.querySelector('[data-e2e="edit-profile-entrance"]'), handle: (document.querySelector('[data-e2e="user-title"]')||{}).innerText }))
  console.log(JSON.stringify(r))
  await page.close(); await b.close()
})().catch(e => { console.error('ERR', e.message); process.exit(1) })
