// ▶️ يخلي فيديو يوتيوب Public من Studio (لما الرفع يسيبه Private). argv: <videoId>
const { chromium } = require('playwright')
;(async () => {
  const b = await chromium.connectOverCDP('http://127.0.0.1:9223', { timeout: 20000 })
  const page = await b.contexts()[0].newPage()
  await page.goto(`https://studio.youtube.com/video/${process.argv[2]}/edit`, { waitUntil: 'domcontentloaded', timeout: 60000 })
  await page.waitForTimeout(8000)
  const vis = page.locator('ytcp-video-metadata-visibility, #visibility-select, ytcp-visibility-select').first()
  await vis.click({ timeout: 20000 }); await page.waitForTimeout(2000)
  const pub = page.locator('tp-yt-paper-radio-button[name=PUBLIC], #privacy-radios tp-yt-paper-radio-button[name=PUBLIC]').first()
  await pub.click({ timeout: 15000 }); await page.waitForTimeout(1200)
  const done = page.locator('#save-button, ytcp-button#done-button, #done-button').first()
  await done.click({ timeout: 10000 }).catch(() => {})
  await page.waitForTimeout(2500)
  const save = page.locator('#save, ytcp-button#save').first()
  if (await save.count()) await save.click().catch(() => {})
  await page.waitForTimeout(5000)
  const t = await page.evaluate(() => document.body.innerText)
  console.log(JSON.stringify({ saved: /Changes saved|saved/i.test(t), visibility: (t.match(/Visibility\s*\n?\s*(Public|Private|Unlisted)/i) || [])[1] || (t.match(/(Public|Private|Unlisted)/) || [])[1] }))
  await page.close(); await b.close()
})().catch(e => { console.error('ERR', e.message.slice(0, 160)); process.exit(1) })
