const { chromium } = require('playwright')
;(async () => {
  const b = await chromium.connectOverCDP('http://127.0.0.1:9223', { timeout: 20000 })
  const page = await b.contexts()[0].newPage()
  await page.setViewportSize({ width: 1400, height: 1000 })
  await page.goto(`https://studio.youtube.com/video/${process.argv[2]}/edit`, { waitUntil: 'domcontentloaded', timeout: 60000 })
  await page.waitForTimeout(8000)
  const ed = page.locator('ytcp-button, button').filter({ hasText: /^Edit draft$/ }).first()
  console.log('edit draft count', await ed.count())
  await ed.click({ timeout: 20000 }); await page.waitForTimeout(6000)
  await page.screenshot({ path: 'output/_yt_draft.jpg', quality: 60, type: 'jpeg' })
  const r = await page.evaluate(() => { const d = document.querySelector('ytcp-uploads-dialog'); return { url: location.href.slice(0, 90), dialog: !!d, dialogVisible: d ? getComputedStyle(d).display : null, dialogs: [...document.querySelectorAll('tp-yt-paper-dialog, ytcp-dialog')].filter(x => getComputedStyle(x).display !== 'none').map(x => x.tagName + ':' + (x.innerText || '').replace(/\s+/g, ' ').slice(0, 120)), next: !!document.querySelector('#next-button'), text: document.body.innerText.replace(/\s+/g, ' ').slice(0, 300) } })
  console.log(JSON.stringify(r)); await page.close(); await b.close()
})().catch(e => { console.error('ERR', e.message.slice(0, 200)); process.exit(1) })
